### PR TITLE
Refactor event listening and fix text-select in Chrome

### PR DESCRIPTION
**Pull request by ErinCall**
This encapsulates #1 as well as making an architectural change that I find more tasteful. If you like my refactor you should merge this and reject #1; otherwise merge #1 and reject this :)

### CODE REVIEW

**Comment by wavebeem** [comment]
Just noticed this PR. I'd be happy to go with this one if you change the single quotes to double quotes and the comment to:

```
// A line comment like this, in sentence case.
```

I'll test this in Chrome/Firefox/IE/Safari in a sec.

**Comment by ErinCall** [comment]
Donezo

**Comment by wavebeem** [comment]
Thanks. Now for testing.

**Comment by wavebeem** [comment]
As stated in IRC, there's still some issues with this in my own testing, but it's closer to correct than my own implementation.

Changing the 0 to 100 in the delay seemed good in my own testing, but I can tweak that outside this issue.

**Pull request merged**
